// tslint:disable-next-line:no-var-requires
import {projectPrefix} from '@shared/model'
const p = projectPrefix + 'FE_'
// const p = 'VUE_'
export const KEY_LANG = p + 'LANG'
export const KEY_IP = p + 'IP'
export const KEY_TOKEN = p + 'TOKEN'
export const KEY_USERNAME = p + 'USERNAME'
export const KEY_PASSWORD = p + 'PASSWORD'
export const KEY_UID = p + 'UID'
export const KEY_TYPE = p + 'TYPE'
export const KEY_API = p + 'API'
export const KEY_SUB_API = p + 'SUB_API_'
export const KEY_WS_USERNAME = p + 'WS_USERNAME'

